# Generated by Django 3.0.6 on 2020-05-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200515_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
