# Generated by Django 3.0.6 on 2020-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Описание комнат'),
        ),
    ]
