# Generated by Django 3.0.6 on 2020-06-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200602_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region_slug',
            new_name='regionslug',
        ),
    ]
