# Generated by Django 3.0.6 on 2020-06-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20200602_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='slug',
            new_name='regionslug',
        ),
    ]
