# Generated by Django 3.0.6 on 2020-06-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20200605_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='regionslug',
            new_name='slug',
        ),
    ]
