# Generated by Django 3.0.6 on 2020-06-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20200605_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='slug',
            new_name='region_slug',
        ),
    ]
