# Generated by Django 3.0.6 on 2020-06-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20200605_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='slug',
            new_name='country_slug',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='slug',
            new_name='hotel_slug',
        ),
    ]
