# Generated by Django 3.0.6 on 2020-06-05 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_auto_20200605_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='region_slug',
            new_name='slug',
        ),
    ]
