# Generated by Django 3.0.6 on 2020-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_auto_20200605_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.SmallIntegerField(default=0),
        ),
    ]
