# Generated by Django 3.0.6 on 2020-06-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование компании партнера')),
                ('img', models.ImageField(upload_to='PartnersMedia', verbose_name='Логотип компании')),
            ],
        ),
    ]
