# Generated by Django 3.0.6 on 2020-06-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='MediaTours/', verbose_name='Фотография')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_discount', to='discount.Discount', verbose_name='Скидки')),
            ],
        ),
        migrations.CreateModel(
            name='TourOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=35)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tours.Tour')),
            ],
        ),
    ]
