# Generated by Django 3.0.6 on 2020-05-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
