# Generated by Django 3.0.6 on 2020-05-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tours', '0003_touraddform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TourAddForm',
            new_name='TourOrder',
        ),
    ]
