# Generated by Django 3.0.6 on 2020-06-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('qoute', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='EmployersMedia/')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('qoute', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='EmployersMedia/')),
            ],
        ),
    ]
