# Generated by Django 3.0.6 on 2020-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_transport_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='price',
            field=models.CharField(default=1, max_length=100, verbose_name='Средняя цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transport',
            name='about',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='img',
            field=models.ImageField(upload_to='MediaCar/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Тип авто'),
        ),
    ]
